python test.py cora
python test.py citeseer
python test.py pubmed
python test.py chameleon
python test.py cornell
python test.py texas
python test.py wisconsin
python test.py Cele
python test.py Ecoli
python test.py NS
python test.py PB
python test.py Power
python test.py Router
python test.py USAir
python test.py Yeast